# Generated by Django 4.2 on 2023-11-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="petlisting",
            name="age",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="petlisting",
            name="breed",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
