# Generated by Django 4.2.7 on 2023-11-15 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelterreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelter_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shelterquestion',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelter_questions', to='shelters.shelter'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petlisting',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='shelters.shelter'),
        ),
        migrations.AddField(
            model_name='petapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petapplication',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='shelters.petlisting'),
        ),
        migrations.AddField(
            model_name='assignedquestion',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_questions', to='shelters.petlisting'),
        ),
        migrations.AddField(
            model_name='assignedquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelters.shelterquestion'),
        ),
        migrations.AddField(
            model_name='applicationresponse',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_responses', to='shelters.petapplication'),
        ),
        migrations.AddField(
            model_name='applicationresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelters.assignedquestion'),
        ),
        migrations.AddField(
            model_name='applicationcomment',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shelters.petapplication'),
        ),
        migrations.AddField(
            model_name='applicationcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
