# Generated by Django 4.2 on 2023-11-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelterquestion',
            name='required',
        ),
        migrations.AddField(
            model_name='assignedquestion',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
