# Generated by Django 4.2 on 2023-11-13 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0002_remove_shelterquestion_required_and_more'),
        ('shelters', '0003_shelterreview'),
    ]

    operations = [
    ]
