# Generated by Django 4.2.7 on 2023-11-27 00:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_petlisting_behavior_petlisting_bio_petlisting_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlisting',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
