# Generated by Django 4.2.7 on 2023-12-05 05:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_petlisting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='petlisting',
            name='image2',
            field=cloudinary.models.CloudinaryField(default='https://i.pinimg.com/736x/c6/de/4f/c6de4fbc92c32c25dd90c41884968d63.jpg', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petlisting',
            name='image3',
            field=cloudinary.models.CloudinaryField(default='https://i.ebayimg.com/images/g/2RwAAOSwCl5jlJE3/s-l1200.webp', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
