# Generated by Django 4.2.7 on 2023-12-05 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_petlisting_image2_petlisting_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlisting',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20)]),
        ),
    ]
